HEADERS_DEMOGRAFICOS = ['#FI_ID_INSTITUCION', 'FI_EMPLEADO', 'FI_PAISCU', 'FI_CANALCU',
       'FI_SUCURSALCU', 'FI_FOLIOCU', 'FC_INSTITUCION', 'FC_NOMBRECOMPLETO',
       'FD_FECHANACIMIENTO', 'FC_PAISNACIMIENTO', 'FC_ESTADONACIMIENTO',
       'FI_EDAD', 'FC_RFC', 'FC_CURP', 'FC_NSS', 'FC_ESTADOCIVIL',
       'FC_ESCOLARIDAD', 'FC_SEXO', 'FC_TELEFONOCASA', 'FC_TELCELULAR',
       'FC_EMAIL', 'FC_AVISOPRIVACIDAD', 'FC_CONSULTABURO',
       'FC_USODATOSPERSONA', 'FC_USODATOSPROMO', 'FC_NACIONALIDAD',
       'FD_ALTAEMPLEADO', 'FI_DATOS_CORRECTOS', 'FI_OFERTA', 'FC_STATUS_EMP',
       'FI_STATUS_EMP', 'FC_NOMBRE_EMPLEADO', 'FC_APELLIDO_PATERNO',
       'FC_APELLIDO_MATERNO', 'FI_ID_PAIS_y', 'FD_FECHA_ALTA',
       'FNPAISNACIMIENTO', 'FNEDONACIMIENTO', 'FNESTADOCIVIL', 'FNESCOLARIDAD',
       'FNSEXO', 'FNNACIONALIDAD']

HEADERS_DISPERSIONES = ['#FI_ID_INSTITUCION_x', 'FI_EMPLEADO', 'FC_CUENTA', 'FD_ULTIMADISPER',
       'FI_TOTALDISPER', 'FN_SALARIO', 'FC_PERIODICIDADPAGO',
       'FI_CAPACIDADPAGO', 'FC_PRODUCTO', 'FI_ID_PRODUCTO', 'FI_CREDITOSACTIV',
       'FIPERIODICIDADPAGO', 'FI_CTA_DIGITOS']

HEADERS_DOMICILIOS = ['#FI_ID_INSTITUCION_y', 'FI_EMPLEADO',
       'FC_CALLEHOGAR', 'FC_NUMEXTHOGAR', 'FC_NUMINTHOGAR', 'FC_COLONIAHOGAR',
       'FC_MUNICIPIOHOGAR', 'FC_ESTADOHOGAR', 'FC_CODIGOPOSTAL', 'FC_PAIS',
       'FI_ID_TIPOVIVIENDA', 'FC_ID_TIPOVIVIENDA', 'FC_LATITUD', 'FC_LONGITUD',
       'FC_SUCURSAL', 'FI_ID_COLONIA', 'FI_ID_MUNICIPIO', 'FC_ID_ESTADO',
       'FI_ID_PAIS_x']